
package com.dwarfeng.test.webservice.server;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FooWebServiceImpl", targetNamespace = "http://server.webservice.test.dwarfeng.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FooWebServiceImpl {


    /**
     * 
     * @return
     *     returns com.dwarfeng.test.webservice.server.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://server.webservice.test.dwarfeng.com/", className = "com.dwarfeng.test.webservice.server.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://server.webservice.test.dwarfeng.com/", className = "com.dwarfeng.test.webservice.server.GetStudentResponse")
    @Action(input = "http://server.webservice.test.dwarfeng.com/FooWebServiceImpl/getStudentRequest", output = "http://server.webservice.test.dwarfeng.com/FooWebServiceImpl/getStudentResponse")
    public Student getStudent();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://server.webservice.test.dwarfeng.com/", className = "com.dwarfeng.test.webservice.server.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://server.webservice.test.dwarfeng.com/", className = "com.dwarfeng.test.webservice.server.HelloWorldResponse")
    @Action(input = "http://server.webservice.test.dwarfeng.com/FooWebServiceImpl/HelloWorldRequest", output = "http://server.webservice.test.dwarfeng.com/FooWebServiceImpl/HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "blocker", targetNamespace = "http://server.webservice.test.dwarfeng.com/", className = "com.dwarfeng.test.webservice.server.Blocker")
    @ResponseWrapper(localName = "blockerResponse", targetNamespace = "http://server.webservice.test.dwarfeng.com/", className = "com.dwarfeng.test.webservice.server.BlockerResponse")
    @Action(input = "http://server.webservice.test.dwarfeng.com/FooWebServiceImpl/blockerRequest", output = "http://server.webservice.test.dwarfeng.com/FooWebServiceImpl/blockerResponse")
    public void blocker();

}
