
package com.dwarfeng.test.webservice.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FooWebServiceImplService", targetNamespace = "http://server.webservice.test.dwarfeng.com/", wsdlLocation = "http://dwarfeng.oicp.net:8989/FooWebService?wsdl")
public class FooWebServiceImplService
    extends Service
{

    private final static URL FOOWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FOOWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FOOWEBSERVICEIMPLSERVICE_QNAME = new QName("http://server.webservice.test.dwarfeng.com/", "FooWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dwarfeng.oicp.net:8989/FooWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FOOWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FOOWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FooWebServiceImplService() {
        super(__getWsdlLocation(), FOOWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FooWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FOOWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FooWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, FOOWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FooWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FOOWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FooWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FooWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FooWebServiceImpl
     */
    @WebEndpoint(name = "FooWebServiceImplPort")
    public FooWebServiceImpl getFooWebServiceImplPort() {
        return super.getPort(new QName("http://server.webservice.test.dwarfeng.com/", "FooWebServiceImplPort"), FooWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FooWebServiceImpl
     */
    @WebEndpoint(name = "FooWebServiceImplPort")
    public FooWebServiceImpl getFooWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.test.dwarfeng.com/", "FooWebServiceImplPort"), FooWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FOOWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FOOWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return FOOWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
