
package com.dwarfeng.test.webservice.helloworld.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldWebServiceImplService", targetNamespace = "http://server.helloworld.webservice.test.dwarfeng.com/", wsdlLocation = "http://127.0.0.1:12450/hello-world?wsdl")
public class HelloWorldWebServiceImplService
    extends Service
{

    private final static URL HELLOWORLDWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HELLOWORLDWEBSERVICEIMPLSERVICE_QNAME = new QName("http://server.helloworld.webservice.test.dwarfeng.com/", "HelloWorldWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:12450/hello-world?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HELLOWORLDWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HelloWorldWebServiceImplService() {
        super(__getWsdlLocation(), HELLOWORLDWEBSERVICEIMPLSERVICE_QNAME);
    }

    public HelloWorldWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public HelloWorldWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDWEBSERVICEIMPLSERVICE_QNAME);
    }

    public HelloWorldWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public HelloWorldWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorldWebServiceImpl
     */
    @WebEndpoint(name = "HelloWorldWebServiceImplPort")
    public HelloWorldWebServiceImpl getHelloWorldWebServiceImplPort() {
        return super.getPort(new QName("http://server.helloworld.webservice.test.dwarfeng.com/", "HelloWorldWebServiceImplPort"), HelloWorldWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldWebServiceImpl
     */
    @WebEndpoint(name = "HelloWorldWebServiceImplPort")
    public HelloWorldWebServiceImpl getHelloWorldWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.helloworld.webservice.test.dwarfeng.com/", "HelloWorldWebServiceImplPort"), HelloWorldWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOWORLDWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HELLOWORLDWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
