
package com.dwarfeng.test.webservice.helloworld.server;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldWebServiceImpl", targetNamespace = "http://server.helloworld.webservice.test.dwarfeng.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldWebServiceImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://server.helloworld.webservice.test.dwarfeng.com/", className = "com.dwarfeng.test.webservice.helloworld.server.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://server.helloworld.webservice.test.dwarfeng.com/", className = "com.dwarfeng.test.webservice.helloworld.server.HelloWorldResponse")
    @Action(input = "http://server.helloworld.webservice.test.dwarfeng.com/HelloWorldWebServiceImpl/HelloWorldRequest", output = "http://server.helloworld.webservice.test.dwarfeng.com/HelloWorldWebServiceImpl/HelloWorldResponse")
    public String helloWorld();

}
