
package com.dwarfeng.test.webservice.concurrent.server;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConcurrentWebServiceImpl", targetNamespace = "http://server.concurrent.webservice.test.dwarfeng.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConcurrentWebServiceImpl {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "concurrentCall", targetNamespace = "http://server.concurrent.webservice.test.dwarfeng.com/", className = "com.dwarfeng.test.webservice.concurrent.server.ConcurrentCall")
    @ResponseWrapper(localName = "concurrentCallResponse", targetNamespace = "http://server.concurrent.webservice.test.dwarfeng.com/", className = "com.dwarfeng.test.webservice.concurrent.server.ConcurrentCallResponse")
    @Action(input = "http://server.concurrent.webservice.test.dwarfeng.com/ConcurrentWebServiceImpl/concurrentCallRequest", output = "http://server.concurrent.webservice.test.dwarfeng.com/ConcurrentWebServiceImpl/concurrentCallResponse")
    public void concurrentCall();

}
