
package com.dwarfeng.test.webservice.concurrent.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConcurrentWebServiceImplService", targetNamespace = "http://server.concurrent.webservice.test.dwarfeng.com/", wsdlLocation = "http://127.0.0.1:12450/concurrent?wsdl")
public class ConcurrentWebServiceImplService
    extends Service
{

    private final static URL CONCURRENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONCURRENTWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CONCURRENTWEBSERVICEIMPLSERVICE_QNAME = new QName("http://server.concurrent.webservice.test.dwarfeng.com/", "ConcurrentWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:12450/concurrent?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONCURRENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CONCURRENTWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ConcurrentWebServiceImplService() {
        super(__getWsdlLocation(), CONCURRENTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ConcurrentWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONCURRENTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ConcurrentWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CONCURRENTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ConcurrentWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONCURRENTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ConcurrentWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConcurrentWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConcurrentWebServiceImpl
     */
    @WebEndpoint(name = "ConcurrentWebServiceImplPort")
    public ConcurrentWebServiceImpl getConcurrentWebServiceImplPort() {
        return super.getPort(new QName("http://server.concurrent.webservice.test.dwarfeng.com/", "ConcurrentWebServiceImplPort"), ConcurrentWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConcurrentWebServiceImpl
     */
    @WebEndpoint(name = "ConcurrentWebServiceImplPort")
    public ConcurrentWebServiceImpl getConcurrentWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.concurrent.webservice.test.dwarfeng.com/", "ConcurrentWebServiceImplPort"), ConcurrentWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONCURRENTWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CONCURRENTWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CONCURRENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
