
package com.dwarfeng.test.webservice.block.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BlockWebServiceImplService", targetNamespace = "http://server.block.webservice.test.dwarfeng.com/", wsdlLocation = "http://127.0.0.1:12450/block?wsdl")
public class BlockWebServiceImplService
    extends Service
{

    private final static URL BLOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BLOCKWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BLOCKWEBSERVICEIMPLSERVICE_QNAME = new QName("http://server.block.webservice.test.dwarfeng.com/", "BlockWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:12450/block?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BLOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BLOCKWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BlockWebServiceImplService() {
        super(__getWsdlLocation(), BLOCKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public BlockWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BLOCKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public BlockWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BLOCKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public BlockWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BLOCKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public BlockWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BlockWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BlockWebServiceImpl
     */
    @WebEndpoint(name = "BlockWebServiceImplPort")
    public BlockWebServiceImpl getBlockWebServiceImplPort() {
        return super.getPort(new QName("http://server.block.webservice.test.dwarfeng.com/", "BlockWebServiceImplPort"), BlockWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BlockWebServiceImpl
     */
    @WebEndpoint(name = "BlockWebServiceImplPort")
    public BlockWebServiceImpl getBlockWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.block.webservice.test.dwarfeng.com/", "BlockWebServiceImplPort"), BlockWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BLOCKWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BLOCKWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BLOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
