
package com.dwarfeng.test.webservice.getobj.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetStudentWebServiceImplService", targetNamespace = "http://server.getobj.webservice.test.dwarfeng.com/", wsdlLocation = "http://127.0.0.1:12450/get-student?wsdl")
public class GetStudentWebServiceImplService
    extends Service
{

    private final static URL GETSTUDENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETSTUDENTWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName GETSTUDENTWEBSERVICEIMPLSERVICE_QNAME = new QName("http://server.getobj.webservice.test.dwarfeng.com/", "GetStudentWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:12450/get-student?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETSTUDENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        GETSTUDENTWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public GetStudentWebServiceImplService() {
        super(__getWsdlLocation(), GETSTUDENTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public GetStudentWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETSTUDENTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public GetStudentWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, GETSTUDENTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public GetStudentWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETSTUDENTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public GetStudentWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetStudentWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetStudentWebServiceImpl
     */
    @WebEndpoint(name = "GetStudentWebServiceImplPort")
    public GetStudentWebServiceImpl getGetStudentWebServiceImplPort() {
        return super.getPort(new QName("http://server.getobj.webservice.test.dwarfeng.com/", "GetStudentWebServiceImplPort"), GetStudentWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetStudentWebServiceImpl
     */
    @WebEndpoint(name = "GetStudentWebServiceImplPort")
    public GetStudentWebServiceImpl getGetStudentWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.getobj.webservice.test.dwarfeng.com/", "GetStudentWebServiceImplPort"), GetStudentWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETSTUDENTWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw GETSTUDENTWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return GETSTUDENTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
